import { Character } from '../character';
import { Series } from '../series';

export type Chant = {
  id: number;
  name: string;
  series: Series;
  volume: number;
  characterIds: Character['id'][];
};

export const chants: Chant[] = [
  {
    id: 1,
    volume: 1,
    name: 'はじまりの詠',
    series: 'tasogare',
    characterIds: [1],
  },
  {
    id: 2,
    volume: 1,
    name: '赤色名詠：アマリリス',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 3,
    volume: 1,
    name: '夜色名詠：アーマ（失敗）',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 4,
    volume: 1,
    name: '赤色名詠：羽根',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 5,
    volume: 1,
    name: '夜色名詠：始まりの女（イヴ）',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 6,
    volume: 2,
    name: '赴戦賛歌（短）',
    series: 'tasogare',
    characterIds: [4],
  },
  {
    id: 7,
    volume: 2,
    name: 'ラスティハイトの独白',
    series: 'tasogare',
    characterIds: [5],
  },
  {
    id: 8,
    volume: 2,
    name: '黎明の神鳥の呼びかけ',
    series: 'tasogare',
    characterIds: [6],
  },
  {
    id: 9,
    volume: 2,
    name: '灰色名詠：王剣・十二銀盤の哮れる日',
    series: 'tasogare',
    characterIds: [5],
  },
  {
    id: 10,
    volume: 2,
    name: '赴戦賛歌',
    series: 'tasogare',
    characterIds: [4],
  },
  {
    id: 11,
    volume: 3,
    name: '赤色名詠：アマリリス（短）',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 12,
    volume: 3,
    name: '緑色名詠：光',
    series: 'tasogare',
    characterIds: [7],
  },
  {
    id: 13,
    volume: 3,
    name: '赤色名詠：黎明の神鳥（ミスクルス）',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 14,
    volume: 3,
    name: '□□□□（その約束に牙剥く者）の真言・大母旧約篇奏——『全ての目覚める子供たち』',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 15,
    volume: 4,
    name: '浸透者の呪詛',
    series: 'tasogare',
    characterIds: [8],
  },
  {
    id: 16,
    volume: 4,
    name: '浸透者への呼びかけ',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 17,
    volume: 4,
    name: '緑色名詠：疾竜（ワイバーン）',
    series: 'tasogare',
    characterIds: [9],
  },
  {
    id: 18,
    volume: 4,
    name: '夜色名詠：黒煙',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 19,
    volume: 4,
    name: '夜色名詠：黒蛇',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 20,
    volume: 4,
    name: '反唱前の一節',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 21,
    volume: 5,
    name: '灰者の王（ラスティハイト）の呪詛',
    series: 'tasogare',
    characterIds: [10],
  },
  {
    id: 22,
    volume: 5,
    name: '虹色名詠：光',
    series: 'tasogare',
    characterIds: [11],
  },
  {
    id: 23,
    volume: 5,
    name: '約束の詠',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 24,
    volume: 6,
    name: '夜色名詠：黒薔薇（花弁）',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 25,
    volume: 6,
    name: '赤色名詠：炎',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 26,
    volume: 6,
    name: '虹色名詠：花束',
    series: 'tasogare',
    characterIds: [11],
  },
  {
    id: 27,
    volume: 7,
    name: '再生能力の発現',
    series: 'tasogare',
    characterIds: [12],
  },
  {
    id: 28,
    volume: 7,
    name: 'アマリリス真言・大母新約篇奏——『全ての目覚める子供たち』',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 29,
    volume: 7,
    name: '赤色名詠：熱妖精',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 30,
    volume: 7,
    name: '名詠門拡張',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 31,
    volume: 7,
    name: '反唱',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 32,
    volume: 7,
    name: '空白名詠：ミクヴェクス真言（セラフェノ音語）',
    series: 'tasogare',
    characterIds: [13],
  },
  {
    id: 33,
    volume: 8,
    name: '夜色名詠：グリフォン',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 34,
    volume: 8,
    name: '灰色名詠：王盾・十二銀盾護れる灰者',
    series: 'tasogare',
    characterIds: [14],
  },
  {
    id: 35,
    volume: 8,
    name: '赤色名詠：赤詠血奏',
    series: 'tasogare',
    characterIds: [15],
  },
  {
    id: 36,
    volume: 8,
    name: '夜色名詠：漆黒の騎士',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 37,
    volume: 9,
    name: '赤色名詠：カルラ',
    series: 'tasogare',
    characterIds: [15],
  },
  {
    id: 38,
    volume: 9,
    name: '虹色名詠：虹色の雪',
    series: 'tasogare',
    characterIds: [11],
  },
  {
    id: 39,
    volume: 9,
    name: '全ての約束された子供たち',
    series: 'tasogare',
    characterIds: [2],
  },
  {
    id: 40,
    volume: 10,
    name: '空白名詠：ミクヴェクス真言',
    series: 'tasogare',
    characterIds: [13],
  },
  {
    id: 41,
    volume: 10,
    name: '夜色名詠：アマデウス',
    series: 'tasogare',
    characterIds: [3],
  },
  {
    id: 42,
    volume: 10,
    name: 'アマデウスへの呼びかけ',
    series: 'tasogare',
    characterIds: [16],
  },
  {
    id: 43,
    volume: 10,
    name: 'Sophit ele Ende',
    series: 'tasogare',
    characterIds: [2, 3],
  },
  {
    id: 44,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／７巻カバー',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 45,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／７巻目次',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 46,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／８巻カバー',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 47,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／８巻目次',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 48,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／９巻カバー',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 49,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／９巻目次',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 50,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／10巻カバー',
    series: 'tasogare',
    characterIds: [],
  },
  {
    id: 51,
    volume: 10,
    name: '緋色の少女の贈奏（エピローグ）／10巻目次',
    series: 'tasogare',
    characterIds: [],
  },
];
